### ISSUE TITLE
Transferability to transformers

### ISSUE THREAD

**Issue by anthony-richardson** [ermongroup/ddim#16]
First of all, thank you for providing the code!
In the according paper I read that the only difference between DDPM and 
DDIM is how samples are generated. 
Intuitively, I would then assume that the CNN model could also 
be replaced by a transformer-type architecture.
If my understanding of your paper is correct, 
one could still use the same simple loss and your DDIM sample generation.
 I would highly appreciate your opinion on this. 
Thanks in advance, Anthony.

**Comment by jiamings** [comment]
Yes. Although I have no idea how a transformer architecture would work on this,

**Comment by anthony-richardson** [comment]
Thanks for you answer. 
Could you clarify what you mean by that statement?
Are you referring to how well it works or do you have concerns regarding the technical implementation?
