### ISSUE TITLE
FID of DDPM on CIFAR-10

### ISSUE THREAD

**Issue by chenweixin107** [ermongroup/ddim#17]
Hi! :)
I wonder with the given configurations, whether we could recover **the FID of 3.17** if we use the code to **train a DDPM from scratch on CIFAR-10**, since I run for 800k steps now and I could only obtain **the FID of about 4**.

**Comment by chenweixin107** [comment]
Also, I found that when generating CelebA images using DDPM with the pre-trained model, the FID is 5.88, which has a margin with that reported in the paper (3.26).

**Comment by chenweixin107** [comment]
I have used the following configurations for DDPM:  --sample_type ddpm_noisy --timesteps 1000 --eta 1

**Comment by jiamings** [comment]
Hi, thanks for your interest! 

Unfortunately, the code we provided for training might not give you the best performance. It is only meant to be used for sampling.
