### ISSUE TITLE
DDIM inversion

### ISSUE THREAD

**Issue by Passenger12138** [ermongroup/ddim#22]
Could you help me in the inversion an image to a gaussion noise

**Comment by egebeysel** [comment]
I think this was resolved here: https://github.com/ermongroup/ddim/issues/9

**Comment by q1nwu** [comment]
Thanks, I have implemented this method

**Comment by gzhu06** [comment]
https://github.com/ermongroup/ddim/issues/9#issuecomment-1503566808

**Comment by Passenger12138** [comment]
Thanks, I have implemented this method
