### ISSUE TITLE
train loss goes very large

### ISSUE THREAD

**Issue by imdoublecats** [ermongroup/ddim#24]
Thank you for your work, but i have a problem.
When i trained with cifar10.yml, the loss went down at first, and the sample result looked normal. But the loss becomed very large after a few steps, and the sample result was full of noise. 
![image](https://github.com/ermongroup/ddim/assets/39366729/13e36ead-23db-4313-8618-0a1447b45e2b)
i also tried to train my custom data but did not meet this problem

**Comment by imdoublecats** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by yinyin-llll** [comment]
hi ,i also trained the model ,but i met the next question
![image](https://github.com/ermongroup/ddim/assets/56313508/a10961ff-f952-4305-90c8-061871e0900b)

and the prompt is python main.py --config cifar10.yml --exp "D:\Anaconda\jupyter notebook\diffusion model\ddim-main" --doc "D:\Anaconda\jupyter notebook\diffusion model\ddim-main\logs" --ni
do you know how to solve the problem?

**Comment by imdoublecats** [comment]
> hi ,i also trained the model ,but i met the next question ![image](https://user-images.githubusercontent.com/56313508/243986459-a10961ff-f952-4305-90c8-061871e0900b.png)
> 
> and the prompt is python main.py --config cifar10.yml --exp "D:\Anaconda\jupyter notebook\diffusion model\ddim-main" --doc "D:\Anaconda\jupyter notebook\diffusion model\ddim-main\logs" --ni do you know how to solve the problem?

seems a path setting problem，but main.py only has 232 lines, how did you get line 300+ traceback?

**Comment by yinyin-llll** [comment]
hh,i added some annotations in main.py.but i have set the path,and i have cretaed the logs file in the catalog,like this 
![image](https://github.com/ermongroup/ddim/assets/56313508/81ae3210-ca15-4b7f-96f3-9ba9968934b1)
and i used the model-790000.ckpt as my train file(put it in logs file and train)
what's your operation about training?

**Comment by jiamings** [comment]
Sorry, the codebase is only used as a reference for sampling, please use some other codebase if you want to achieve high quality training.

**Comment by imdoublecats** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
