### ISSUE TITLE
run sampling process with cifar10 dataset

### ISSUE THREAD

**Issue by Sugar929** [ermongroup/ddim#26]
Hi! :)  I wonder if there were ckpt of model trained on cifar10?

I tried to use _diffusers_ from huggingface, but there were some problem with my network so I couldn't download it from the hub.

And also I want to observe layer's activation distribution during sampling(DDIM on cifar10), so the integrated _diffusers_ probably can't achieve this goal.

thx

**Comment by jiamings** [comment]
The checkpoint is the same as the one used in Patrick's repo (https://github.com/pesser/pytorch_diffusion).
