### ISSUE TITLE
Generation Process not producing quality images.

### ISSUE THREAD

**Issue by VishyTheFishy** [ermongroup/ddim#27]
I have been training on the CIFAR-10 dataset, and no matter how far I train, it continues to generate images which look like this:

![428](https://github.com/ermongroup/ddim/assets/69478716/df85df89-2b7d-449a-93e8-d98b71dbcbf7)

Is this a possible issue with the image generation pipeline, or is it a problem with the model not training correctly?

**Comment by cannacak** [comment]
I have the same problem ? Any solution ?

**Comment by jiamings** [comment]
The training code might not be very high quality due to DDIM being mostly a sampling methods that reuses pretrained checkpoints.
