### ISSUE TITLE
Questions about noise distributions during training and sampling

### ISSUE THREAD

**Issue by gitwangxf** [ermongroup/ddim#28]
Hi, thanks for your exciting work!
I found that during sampling of a trained diffusion model, replacing the gaussian noise distribution by uniform distribution would encourage more diverse samples.  I'm wondering that from Eq. (12) of this paper, is it reasonable to infer that apart from σ, we can also change the noise distributions during sampling without re-training the model?
![image](https://github.com/ermongroup/ddim/assets/93958139/a9645eb9-ea27-403d-9f56-a4331b6bba66)

**Comment by jiamings** [comment]
It might depend on how you add the uniform distribution. Would the sum of uniform noise still be a uniform noise in the diffusion process?
