### ISSUE TITLE
Could you please provide guidance on the calculation of FID?

### ISSUE THREAD

**Issue by xzmy-Dreamleft** [ermongroup/ddim#29]
Hello, I greatly appreciate your selfless sharing of this GitHub repository; it has been immensely beneficial for my learning progress. However, I am currently unclear on how to calculate the Fréchet Inception Distance (FID) metric using your code as a foundation. Would it be possible for you to provide some guidance or recommendations on how to perform FID calculations?

Thank you very much for your contributions.

**Comment by jiamings** [comment]
I used https://github.com/toshas/torch-fidelity for this.

**Comment by xzmy-Dreamleft** [comment]
Thank you very much for your guidance! I used the CelebA 64 x 64 model you provided on GitHub, but I found that the images generated by the model scored over 30 when calculating the FID compared to the images from the CelebA dataset. I believe there might be some mistakes on my part, and I hope you can provide some guidance.
Could I trouble you to offer some guidance once again? And thank you for your previous generous assistance!
