### ISSUE TITLE
Regarding the issue of excessive FID

### ISSUE THREAD

**Issue by xzmy-Dreamleft** [ermongroup/ddim#30]
Thank you very much for your  guidance in #29 ! But after that, I encountered other issues.I can't calculate the correct FID score.
 I used the CelebA 64 x 64 model you provided on GitHub, but I found that the images generated by the model scored over 30 when calculating the FID compared to the images from the CelebA dataset. I believe there might be some mistakes on my part, and I hope you can provide some guidance.
Could I trouble you to offer some guidance once again? And thank you for your previous generous assistance!

**Comment by xzmy-Dreamleft** [comment]
Additionally:
My sampling command is "python main.py --config celeba.yml --exp ./ --doc celeba_train --sample --fid --timesteps 1000 --eta 0 --ni," and I used the CelebA 64 x 64 model provided by you directly for sampling.

**Comment by xzmy-Dreamleft** [comment]
I have resolved the issue; it was just a mistake in the data preprocessing stage. Thank you for your assistance.

**Comment by WeizhenWang-1210** [comment]
@xzmy-Dreamleft Hi, I run into a similar issue, and I'm wondering if you can describe how you created the CelebA 64 benchmark. What preprocessing did you perform? Did you use the entire 200k images or only the train split? Much appreciated
