### ISSUE TITLE
Question in results

### ISSUE THREAD

**Issue by zzw-zwzhang** [ermongroup/ddim#6]
Hi, I used your default parameters to train the DDIM model using 1000 diffusion steps, 800k iterations.

But my reproduced results are very bad, can you provide some suggestions?

fidelity --gpu 9 --fid --input1 exp/image_samples/baseline_cifar10/ --input2 cifar10-train --sample_type generalized

FID: 187.58

**Comment by jiamings** [comment]
Maybe try the pretrained model first? Our paper presents a guideline mostly for sampling but not necessarily for training. That being said, the default training values should be the one from the DDPM paper.
