### ISSUE TITLE
Question in the paper

### ISSUE THREAD

**Issue by sunwoo76** [ermongroup/ddim#8]
I have a question in Table1 in this paper.

In the table1, the cases of eta=1 and hat{sigma} are the case of DDPM.
However, the performances of these cases are different.

What are the differences between those cases?
![화면 캡처 2022-06-15 161148](https://user-images.githubusercontent.com/38250239/173766028-2021b90c-b28c-41ea-a3e3-a38a842de8cd.jpg)
)

Thank you :

**Comment by jiamings** [comment]
These are the two variances considered in the DDPM paper. The bottom row corresponds to the larger variance used (which is the one used in the DDPM CIFAR10 results, hence the lower FID).
